stone-lock : EMERALD
stone-unlock : MAGMA_CREAM
item-list : 
- WOOD_SWORD
- STONE_SWORD
- IRON_SWORD
- DIAMOND_SWORD
- GOLDEN_SWORD
- BOW
- WOOD_AXE
- STONE_AXE
- IRON_AXE
- DIAMOND_AXE
- GOLDEN_AXE
- LEATHER_HELMET
- LEATHER_CHESTPLATE
- LEATHER_LEGGINGS
- LEATHER_BOOTS
- CHAINMAIL_HELMET
- CHAINMAIL_CHESTPLATE
- CHAINMAIL_LEGGINGS
- CHAINMAIL_BOOTS
- IRON_HELMET
- IRON_CHESTPLATE
- IRON_LEGGINGS
- IRON_BOOTS
- DIAMOND_HELMET
- DIAMOND_CHESTPLATE
- DIAMOND_LEGGINGS
- DIAMOND_BOOTS
- GOLDEN_HELMET
- GOLDEN_CHESTPLATE
- GOLDEN_LEGGINGS
- GOLDEN_BOOTS
- WOOD_PICKAXE
- STONE_PICKAXE
- IRON_PICKAXE
- GOLDEN_PICKAXE
- DIAMOND_PICKAXE
- WOOD_SHOVEL
- STONE_SHOVEL
- IRON_SHOVEL
- DIAMOND_SHOVEL
- GOLDEN_SHOVEL
- SHEARS
- WOOD_HOE
- STONE_HOE
- IRON_HOE
- DIAMOND_HOE
- GOLDEN_HOE
- FISHING_ROD
- LEAD
- ELYTRA